### ISSUE TITLE
German Language Synthdog

### ISSUE THREAD

**Issue by ChrisDelClea** [clovaai/donut#161]
Hey Folks, 

this is great stuff. I wanted to request a german train-dataset for it. 
Is it possible you could generate the German version for it? 
If possible, also include german in the next generation of donut.

Best regards
Chris

**Comment by meugeny** [comment]
@ChrisDelClea 
You can generate German language SynthDoG by yourself. 
Watch instruction in SynthDoG readme.md: https://github.com/clovaai/donut/tree/master/synthdog.
I created Russian dataset this way. Simply created new config_ru.yaml, added russian text corpus and fonts, then clone synthdog repository and run script, where select new config.

**Comment by meugeny** [comment]
@ChrisDelClea i took corpus of newspaper articles with size 7 MB.
Also I change tokenizer to include my language tokens.

**Comment by meugeny** [comment]
@ChrisDelClea 
Initialization of model, processor from huggingface, replace tokenizer
```ruby
config = VisionEncoderDecoderConfig.from_pretrained("nielsr/donut-base")
processor = DonutProcessor.from_pretrained("nielsr/donut-base")
model = VisionEncoderDecoderModel.from_pretrained("nielsr/donut-base", config=config)
tokenizer = AutoTokenizer.from_pretrained('DeepPavlov/xlm-roberta-large-en-ru')
processor.tokenizer = tokenizer
```
Results after one epoch (27777 batches of 3 Synthdog images on 2 GPU)
![image](https://user-images.githubusercontent.com/79811220/227704450-56b96f87-4f21-441f-a7ff-f4501a5805c1.png)

**Comment by sjtu-cz** [comment]
@meugeny where can download the language otf font file?

**Comment by meugeny** [comment]
@sjtu-cz for example, here https://www.fontsquirrel.com/

**Comment by lkutsenok** [comment]
@meugeny can you share the instructions on how to prepare the dataset and then train donut on it? Or maybe a notebook

**Comment by meugeny** [comment]
@lkutsenok I used this notebook https://github.com/NielsRogge/Transformers-Tutorials/tree/master/Donut/CORD
You can find instructions, how to prepare dataset on Donut's official repo https://github.com/clovaai/donut

Big problem was to generate correct json. All quotation marks must be equal. You can see example when you generate SynthDoG dataset. JSON will be created automatically. 
Or here https://huggingface.co/datasets/naver-clova-ix/cord-v1/viewer/naver-clova-ix--cord-v1/train

**Comment by rm-asif-amin-bkashEDA** [comment]
Hi @meugeny . I'm about to replicate your workflow. Thank you very much for sharing it. 

I've already fine-tuned an English version using [this model](https://huggingface.co/naver-clova-ix/donut-base-finetuned-cord-v2) as a base.  It works pretty good. For the same type of documents, I want to prepare it for Bengali language. Since the donut-base supports only 4 languages (en, ko, jp,zh), will it be enough to use a tokenizer that supports bengali only?

My current thought process is this-

-  Generate Synthetic dataset using Sythdog 
-  Use my model that's already finetuned with English documents as base.
-  Train it to parse all the text in the Synthdog documents.
-  Finetune with Docsim generated documents that actually resemble document format to finetune on information extraction task.

My questions are-

1. Can I use [this ](https://huggingface.co/ai4bharat/IndicBART) model for the tokenizer? What modifications do I need to do to use it as the text decoder model as this supports bengali?
2. Do you use Synthdog generated documents to just teach it how to read? or on the actual downstream task?

**Comment by meugeny** [comment]
@rm-asif-amin-bkashEDA I'm not sure I can correct answer your questions, but
1. I have tried to replace Donut tokenizer by ai4bharat/IndicBART and it correctly tokenizes Bengali. So you can try it.
```ruby
from transformers import AutoTokenizer
from transformers import DonutProcessor,
processor = DonutProcessor.from_pretrained("naver-clova-ix/donut-base")
tokenizer = AutoTokenizer.from_pretrained("ai4bharat/IndicBART", do_lower_case=False, use_fast=False, keep_accents=True)
processor.tokenizer = tokenizer
tokenizer.batch_decode(tokenizer.encode("আমি সঙ্গীত পড়ি"))
```
You don't change text decoder, you just replace tokenizer. To understand, how it works, you can watch https://www.youtube.com/watch?v=IGu7ivuy1Ag&t=1669s
2. Yes, I used SynthDog dataset to teach model understand new language. And then I created downstream task on document dataset.

**Comment by sohambhal** [comment]
@meugeny Would you mind sharing your notebook for training the new Russian language? I have tried to replicate but haven't succeeded so far, this is what I get:

![Epochs](https://user-images.githubusercontent.com/39585639/230661703-494e106b-91d0-4026-ae74-cc099055e868.png)

**Comment by rm-asif-amin-bkashEDA** [comment]
@meugeny thanks a lot. Went through the video you linked. Very informative!

We're working on the first part that you mentioned. Just to clear up- 

when you say "teach model understand new language", is it fine-tuning the donut-base model for a <s_synthdog> task  as mentioned in this [issue](https://github.com/clovaai/donut/issues/62)? And then again finetuning on downstream task?

**Comment by meugeny** [comment]
> @meugeny thanks a lot. Went through the video you linked. Very informative!
> 
> We're working on the first part that you mentioned. Just to clear up-
> 
> when you say "teach model understand new language", is it fine-tuning the donut-base model for a <s_synthdog> task as mentioned in this [issue](https://github.com/clovaai/donut/issues/62)? And then again finetuning on downstream task?

Yes, as I understand, "teaching model understand new language" is fine-tuning, and then fine-tuning on downstream task.
Issue, you send, is about inference, not finetuning.

**Comment by rm-asif-amin-bkashEDA** [comment]
@meugeny sorry for the confusion. Yes the issue is about inference. They mentioned that they used the <s_synthdog> tag to infer the whole text. I wanted to ask whether I should finetune using the same tag. I.E.:

train for the task of predicting the full image text using the <s_synthdog> tag? Did you use this (<s_synthdog> ) tag in particular? or can i use any arbitrary tag i want?

**Comment by meugeny** [comment]
@sohambhal I used notebook by NielsRogge, as I mentioned before, and added tokenizer for cyrrilic symbols.
Maybe you can share your notebook?

**Comment by meugeny** [comment]
@ChrisDelClea NielsRogge's notebook already can take input format described in Donut's Github.
Tokenizer code example you can see above.

**Comment by BakingBrains** [comment]
@meugeny Thanks for the info, but I tried to finetune on Hindi language with Hindi tokenizer, but got junk output.

Number of training image - (4000 generated from synthtiger)
Epochs - 50
Rest of the training configuration is same.


Any suggestions here?

**Comment by meugeny** [comment]
@BakingBrains, Hi, did you check how tokenizer encodes text to tokens? 
Did you plot logs? What do they look like?

**Comment by BakingBrains** [comment]
@meugeny Yes json annotations are correct. No I generated it using SynthTiger (https://github.com/clovaai/synthtiger)
I have not checked the tokens encoded from tokenizer. I am using bhavikardeshna/xlm-roberta-base-hindi as tokenizer.
Can you please specify what do you mean by plot logs?

**Comment by BakingBrains** [comment]
@meugeny tokens are correct.
![image](https://user-images.githubusercontent.com/51019420/233862109-b53ad80b-863a-4873-a758-4fd395073837.png)

**Comment by meugeny** [comment]
@BakingBrains I mean to look on losses' and val_metrics' plots on wandb. What is their behavior?

**Comment by rm-asif-amin-bkashEDA** [comment]
Hi @meugeny !
Hope you're doing great. I've been working on the project since we last talked. As per your suggestion, I've used a tokenizer that correctly tokenizes for my language. I had some trouble with Synthdog(working to fix it), so opted for Synthtiger instead. The images I trained on therefore are text on white background. 

I've been using [this](https://www.philschmid.de/fine-tuning-donut) blog as a reference and recreated the whole flow in [this](https://colab.research.google.com/drive/1V_vP4p3W874QTSN-EYHOg-t4XGYR8TlP?usp=sharing) notebook to better communicate with you. My model's predictions on the basic text parsing task are almost gibberish, for example-

```
Target-
 \<s><s_bn_text>শুধিয়েছিলাম আকতারুজ্জমান ন্যাপকিনগুলোও টিস্যুতে চিরকুটগুলোর এলেনও আওটাতিস গালেও গোলটায় নন্দকুজা ভাবলীলা আবাসে কোস্টলি পুরুজ্জীবিত ইফেনবার্গ কাবিলাপাড়া গিন্সবার্গ লোকেই থুক্কু ঝোলাবো টেরচা অজানাকে সারাইয়াছিলি গোবিন্দা রামধনগর টার্টি নাহারপুঞ্জির ফোঁপাচ্ছে তথ্যানুযায়ী প্রত্যাশামতো পুলেন ভয়েসে বিলাশ অস্ত্রশিক্ষায় বোঝাচ্ছ গুলিতেছিলেন টিপসই অর্ধাংশ শিক্ষালয়ে টিএআরপি দ্যাহে মোহন্তেরহাট তিনজনেরও জগপতি নৈপুণ্যধারী হাবার পররাষ্ট্রসচিবদের ধানসিড়ি মোহাবাতুন্নেছা রেইনসি টুকিয়াছিলি প্রযোজকের নিরাপদ্‌ নীলোর্মী নারীনেতৃত্ব বিশকেতে যুগলবন্দিতে বিএলআরসি হিমালয়ভিত্তিক জমিলার চিত্রসম্পাদনে হিজলাকর লেখকজীবনে পরোপকারক হারাচ্ছিলুম ল্যাদ্দিতে ইদেলকাঠি অপরিমেয় টেলিফোনবার্তায় নব্যতা বিট্লা রিজুয়ানুর মুঙ্গির কূটনীতিকেরাও শিক্ষিকারাও নিঃসরণজনিত কাঁদাইতিস ক্লিনিকটা গোঙাল ব্যক্তিস্বার্থে ড্রামলাইন কশিয়াছিলে প্রযোজকদের জোডি সাঁৎলাইয়া হজযাত্রার হারিশ চকঘোগা ঝিমচ্ছ ভেংচাচ্ছিলে পরিপ্লব আগমনীর অর্থোসার্জারি তাম্বুলবুনিয়া মিগনন সিপিটিইউর বাকস্ফুর্তি সাহিত্যও নাৎসি কোঁচাবার সেলুলোজিক্যাল জড়বুদ্ধি ডর্থি পিএডির রামাদি মেহেদুল একনাথ ক্লেভিল্যান্ডের মালেশিয়া ফেলছিলি সিট্‌কবেন ছাপিয়াছে পুরিয়াছেন প্রতিযোগিতাও ঢাকাফোন জামবাড়িয়া রৌতের সুভাষচন্দ্র গনের রূপটান পশুকেন্দ্রিকতা ছ্যাড়ি পরমানিক কারভ্যানটেস রবিনটেক্স হাতিরপুলের মেজবা শামসুজ্জোহার ছাপাচ্ছিলাম ছুড়ছিলি
</s_bn_text></s>

Prediction-
 \<s><s_bn_text> টেরোগলিক টেরোগম্ ড়াইয়াছিলেম ঢলিক টেম্পোম্ ড়াইয়াছিল ড়াইয়াছিল টেম্পোলাইয়াছিল টেম্পোলা টেম্পোলাইয়াছিলেম টেম্পোলা টেম্পোলাইয়াছিলেম্ ধারাও ধারাও ধারণকেইয়াছিলেম্ ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ঢল্ ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ঢল্ ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম ড়াইয়াছিলেম টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেন টেক্যাপুব্ টেক্যাপুব্ টেক্যাপুব্ টেক্যাপু<s_bn_text>কে বি<s_bn_text> বি<s_bn_text> বি<s_bn_text> বি<s_bn_text> বি<s_bn_text> বি<s_bn_text> টেক বি<s_bn_text> বি<s_bn_text> বি<s_bn_text> বি<s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text><s_bn_text></s>`
```
Another example-

```
 Target-
 <s><s_bn_text>গুণটাও লট্‌কাত কিছুদূরে বাগুন টিএন্ডটি দশকভিত্তিক তৈয়বার ডিসঅর্ডারের তুষারপথে কাগয খায়ছি জামায়াতনিয়ন্ত্রিত বিলন কারিগরে জীবনাদর্শনে পিষচ্ছিলেন মন্ত্রীরা গোপনেত সল্যুশন্স অর্থনীতিই সামাজ্যবাদ ভূভৃৎ ফরম্যাটিং কওনই মাসানোরি হাঁসাইলি জুলোজি স্পাইডারম্যান চটপটিসহ মেফিড্রিন যুবতি শিক্ষাবার্তার দুলা উদিনেসে মুস্তাহিদুর ধরাইতেছিস মানবই চক্রপথের চষিয়াছিল স্ট্যালেকটাইটের বুলেটকেও বেক্সিমকো সুইপুরা রাব্বানীর ফেলি পুলুদনিসন এঅ্যান্ডএম দারিদ্র্যসীমা মিনেচেম উপদেশদানকারী দরপ্রস্তাবে জিনিসগুলান মাহীরাজ মরা বিরমপাশা ছাওয়ালডাক কিনানো আনারুলের ধম্‌কাতাম গদাইপুর ঘুরিলেন পরিবেষণ রুমন ধলই টাটাইবি শ্রীঅঙ্গনে গুঁড়িয়ে শীর্ষবিন্দুটার আগাচ্ছি উচ্চভিলাষী সাদীরচর নির্বাসনেই নিকটদৃষ্টির জনমিতির বোঝাচ্ছিলাম কশাইলে ঘুলনো ওয়াটের আর্থরাজনৈতিক টাইমস অংশএবং কৃত্যানুষ্ঠানে খাঁজ রটাইতেছিলেন উপকারও মালয়েশিয়ায়ই দেওয়াইয়াছিল গণতন্ত্রচর্চায় ইয়াহিহয়া তফাৎ ফোরজি উদ্ভাবকের সংসদগামী হাভ্রের ক্ষান্তি নিজির আইনবহির্ভূতভাবে কোলোনের দাভা সাদুল্যাপুরে টোঙ্গাতে মিরাশদারের মিশায়ে রাওয়ালপিণ্ডিতে সাজ্জেদুল কিজমান স্পিনেই সবর পপআপ থুব্‌ড়াইবি নাহান গ্লেজ চালকুমড়ো মেঙ্গেছিলুম তাওকীর প্রদীপে অঞ্চলগুলোয় পাটকাঠী ঘুরেছিস ঝাঁকিয়াছে বাঁকালাম টেবিলটাও রণি মাসআলাতি জাদুকরী ফ্র্যাঙ্কো নির্বাহীকেও হয়রানিবিষয়ক নাগরিকত্বের উড্ডয়নসংকটে
</s_bn_text></s>

Prediction-
 <s><s_bn_text> ঠকাইবেষিয়েছিলেম টেক বিস্নাইতেছিলেম ঠকাশুদ্ধের ঠকাশটিক ঠকাশমাখালীতেছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম ঠকাইয়াছিলেম ঠকাইয়াছিলেম ঠকাইয়াছিলেম ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠি ঠকাইয়াছিলেম্ ঠি ঠি ঠকাইয়াছিলেম্ ঠি ঠি ঠি ঠকাইয়াছিলেম্ ঠি ঠি ঠি ঠি ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠি ঠি ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেম্ ঠকাইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোইয়াছিলেমতোর ঠকাইয়াছিলেমতোর ঠকাইয়াছিলেম ঠকাইয়াছিলেম ঠকাইয়াছিলেম ঠকাইয়াছিলে ঠকাইয়াছিলেমকেন্দ্রে ঠকাইয়াছিলেম্মোরাও ঠকাইতেরাও ঠকাইতেরাও ঠকা<s_bn_text> শিশুরারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারারা</s>

```
It's almost gibberish, but seems like there are glimpses of learning there.

It would be great to hear your opinion on my [notebook's](https://colab.research.google.com/drive/1V_vP4p3W874QTSN-EYHOg-t4XGYR8TlP?usp=sharing) pipeline. I've printed clear outputs for each step. 

1. Do you observe any possible errors in my notebook or steps i could improve or steps you would do differently?
2. Do you think it might be just a data problem(since I've only trained with 10,000 images)? 
3. How many images did you use and how much time did it take? For my 10k images it took almost 36 hours with 4 gpus and data parallelism.

Here's my training loss plot-
![image](https://user-images.githubusercontent.com/62927473/235494667-76adea18-a838-46b2-b688-3a4686e4d1a4.png)

Looking forward to hearing from you!

Best

**Comment by kurbobo** [comment]
>
@meugeny
Hello, how does the model perform on Russian language?
And could you please share the link to the corpus with newspaper articles?
Thanks in advance!

**Comment by meugeny** [comment]
@rm-asif-amin-bkashEDA I trained on new language for at least 200000 steps and 100000 images on Kaggle. 
I see your loss is falling down, so i guess you should continue to train and watch progress.

**Comment by rm-asif-amin-bkashEDA** [comment]
@meugeny thanks for the info. Will try to train for longer and see what happens.

**Comment by rm-asif-amin-bkashEDA** [comment]
@meugeny I solved the issue. It now works for the downstream task too. It was due to using a custom function that was not returning compatible types when supplied to the datasets.map() function in batched streaming mode. It was okay for non-batched mode though thus throwing no errors. The documentation wasn't clear on this.

Rewriting the custom function to match the specs on documentation solved it.

**Comment by thaodod** [comment]
@rm-asif-amin-bkashEDA Can you please share your successful notebook with me? I tried to finetune for page parsing in Vietnamese but still high ED (bad result) so far. tried several configure and also created synthetic data, but yet, still bad result. (30 epochs, take huge amount of time). Please help.

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~
