### ISSUE TITLE
Local custom dataset & Potential typo in test.py

### ISSUE THREAD

**Issue by xingjianz** [clovaai/donut#4]
Hi, thanks for this interesting work!
I tried to use this model on a local custom dataset and followed the dataset structure as specified but it failed to load correctly. I ended up having to hard code some data loading code to make it work. It would be greatly appreciated if you guys can provide a demo or example of local dataset. Thanks!

PS: I think there may be a typo in the test.py: the '--pretrained_path' should probably be '--pretrained_model_name_or_path' ?

**Comment by gwkrsrch** [comment]
Hi, thank you for the issue :)

**1, Local custom dataset.**
We use [huggingface/datasets](https://github.com/huggingface/datasets) for loading & processing the dataset.
As explained in the README, if you set metadata.jsonl and image_paths properly, there would be no problem.
This [link](https://huggingface.co/docs/datasets/v2.3.2/en/image_process#imagefolder-with-metadata) would be helpful to you. If you still have an error, please share the details, e.g., error messages, so that I can help you.

**2, pretrained_path in test.py.**
Thanks for pointing it out. There is no critical issue with the argument name. Still, I think it would be better to change the name to reduce any miss understanding. I will update the name.

Hope this helps :) Please let me know if you are still confused.
