### ISSUE TITLE
Which OCR works in inference internally ?

### ISSUE THREAD

**Issue by deepanshudashora** [clovaai/donut#50]
I wanted to know which OCR it uses internally for training or inference, It claims to OCR free VDU but how it understands the coordinates and text in that case while inferencing the image, basically getting what text is written there while inference is necessary (According to my assumption)

**Comment by logan-markewich** [comment]
It's "OCR Free" because no external OCR tool is used. There is no internal tool.

Traditionally, you might use something like Tesseract to perform OCR and pass that output to another model

Donut is trained to perform OCR by itself (details in their paper), and then fine-tuned for tasks like VQA. Therefore, no external OCR tool is needed, which saves a ton of computation time and reduces error propagation. The model reads the document and performs the task in a single step.
