### ISSUE TITLE
Fictitious results when trying to infer from an image with the wrong orientation

### ISSUE THREAD

**Issue by adinath-auti** [clovaai/donut#64]
Hi,

We've fine-tuned donut to infer text from a specific class of document and under normal conditions it works very well, however when trying to infer from an image with the wrong orientation (especially when upside down), the model outputs completely fictitious results, albeit ones that fit the format perfectly.

Any insights on how this happens?

**Comment by adinath-auti** [comment]
Alright, but how can one detect/flag these cases? The output donut generates is realistic enough to pass by a human moderator. If you want examples I can DM them but I cannot post them publicly.

**Comment by logan-markewich** [comment]
@adinath-auti [one option](https://pyimagesearch.com/2022/01/31/correcting-text-orientation-with-tesseract-and-python/) is to use tesseract to detect text orientation before passing to donut, but that kind of defeats the purpose of using donut. If you go down the route of using tesseract (or whichever OCR service you want), I would use a model like LayoutLMV2 or LayoutLMV3.

As another option, [this stack overflow post ](https://stackoverflow.com/questions/55654142/detect-if-an-ocr-text-image-is-upside-down)covers a lot.

Depending on what your inputs look like, you could look for white-space on the page, which would be much faster than using tesseract. Pages will have more white-space on the bottom, so if you detect a lot of white-space on the top then rotate it.

You can also use cv2 to detect the skew, but 0 degrees and 180 degrees will look the same to the algorithm in this approach.

Lastly, maybe it's worth trying to calculate how common this problem is before putting in a lot of effort to fix it. Is it worth the effort of fixing? Can your system/app accept some error?

**Comment by adinath-auti** [comment]
On further investigation throughout the training dataset, the model seems like it is generating these results by borrowing bits from images with the wrong orientation (i.e:- the names it generates look sensible but are actually composed of parts/substrings of names it saw in images with incorrect orientation in the training dataset). We will try to re-train using augmented data to see if we can address this. Thank you for your help.

**Comment by Codedrainer** [comment]
Hi @adinath-auti , have you found the solution for this
