### ISSUE TITLE
How much time OCR takes?

### ISSUE THREAD

**Issue by htcml** [clovaai/donut#85]
In the Donut paper, the table 1 shows Donut takes 752 ms vs 1489 ms by LayoutLMv2. Could you tell me in this benchmark, OCR portion takes up how much time?

**Comment by gwkrsrch** [comment]
It was approximately ~1.35. Since RVL-CDIP (industrial documents) tend to have more text, It took more time than CORD (Indonesian receipts) on average. Appendix A.1 would be helpful to you. You can measure it by yourself. It might be slightly different as the API might have been upgraded, but you will get a similar overall result. Hope this helps :)
